name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Restore Astro cache
        uses: actions/cache/restore@v4
        with:
          path: build_cache
          key: ${{ runner.os }}-astro-cache
          restore-keys: |
            ${{ runner.os }}-astro-

      - name: Install dependencies
        run: npm ci

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_WEBSITE_2FC30 }}
          channelId: live
          projectId: website-2fc30
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks

      - name: Save Astro cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: build_cache
          key: ${{ runner.os }}-astro-cache
